Movie_details:
    Default_list_size :    7
    Default_font_size :   10
    Result_size :   12
    Movie_list_dropdown :    ["American Beauty (1999)",
                              "Star Wars: Episode IV - A New Hope (1977)",
                              "Jurassic Park (1993)",
                              "Saving Private Ryan (1998)",
                              "Terminator 2: Judgment Day (1991)",
                              "Back to the Future (1985)",
                              "Silence of the Lambs, The (1991)",
                              "Braveheart (1995)",
                              "Schindler's List (1993)",
                              "Dog Park (1998)",
                              "Superman (1978)"]
Action : ['Star Wars: Episode IV - A New Hope (1977)',          
            'Jurassic Park (1993)',
            'Saving Private Ryan (1998)',
            'Terminator 2: Judgment Day (1991)',
            'Matrix, The (1999)',
            'Men in Black (1997)',
            'Raiders of the Lost Ark (1981)',
            'Braveheart (1995)',
            'Princess Bride, The (1987)',
            'Star Wars: Episode I - The Phantom Menace (1999)',
            'Godfather, The (1972)',
            'Star Wars: Episode VI - Return of the Jedi (1983)',
            'Terminator, The (1984)',
             'Alien (1979)',
            'Total Recall (1990)',
            'Fugitive, The (1993)',
            'Star Wars: Episode V - The Empire Strikes Back (1980)',
            'Gladiator (2000)',
            'Aliens (1986)',
            'Independence Day (ID4) (1996)']
Comedy : ['American Beauty (1999)',
            'Back to the Future (1985)',
            'Men in Black (1997)',
            'Shakespeare in Love (1998)',
            'Princess Bride, The (1987)',
            'Groundhog Day (1993)',
            'Being John Malkovich (1999)',
            'Forrest Gump (1994)',
            'Ghostbusters (1984)',
            'Toy Story (1995)',
            'Stand by Me (1986)',
             'Babe (1995)',
            'Airplane! (1980)',
            'Galaxy Quest (1999)',
            "Bug's Life, A (1998)",
            'Lethal Weapon (1987)',
            'Monty Python and the Holy Grail (1974)',
            'Toy Story 2 (1999)',
            'When Harry Met Sally... (1989)',
            'Breakfast Club, The (1985)']
Horror : ['Ghostbusters (1984)',
            'Alien (1979)',
            'Jaws (1975)',
            'Psycho (1960)',
            'Blair Witch Project, The (1999)',
            'Rocky Horror Picture Show, The (1975)',
            'Young Frankenstein (1974)',
            'Shining, The (1980)',
            'Fly, The (1986)',
            'Sleepy Hollow (1999)',
            'Mummy, The (1999)',
            'Army of Darkness (1993)',
            'Little Shop of Horrors (1986)',
            'Alien³ (1992)',
            'From Dusk Till Dawn (1996)',
            'Scream (1996)',
            'Exorcist, The (1973)',
            'Misery (1990)',
            "Devil's Advocate, The (1997)",
            'Blade (1998)']
Drama : ['American Beauty (1999)',
            'Star Wars: Episode V - The Empire Strikes Back (1980)',
             'Saving Private Ryan (1998)',
            'Silence of the Lambs, The (1991)',
            'Fargo (1996)',
            'Braveheart (1995)',
            "Schindler's List (1993)",
            'E.T. the Extra-Terrestrial (1982)',
            'Shawshank Redemption, The (1994)',
            'Godfather, The (1972)',
            'Pulp Fiction (1994)',
            'Gladiator (2000)',
            'Stand by Me (1986)',
            'Babe (1995)',
            "One Flew Over the Cuckoo's Nest (1975)",
            'Wizard of Oz, The (1939)',
            '2001: A Space Odyssey (1968)',
            'Godfather: Part II, The (1974)',
            'Casablanca (1942)',
            'GoodFellas (1990)']